### ISSUE TITLE
helloworld failed to run with qemu/arm64

### ISSUE THREAD

**Issue by SorinAlexB** [unikraft/app-helloworld#31]
When trying to run with qemu/arm64 the error "platform kvm requested but it's not available" pops up.

If i try to run it manually with 'qemu-system-aarch64 -kernel .unikraft/build/helloworld_qemu-arm64 -nographic -machine virt -cpu max' it works fine without any error.

**Comment by Mihnea0Firoiu** [comment]
I have the same issue.

NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

Linux ArchLinux 6.1.58-1-lts #1 SMP PREEMPT_DYNAMIC Sun, 15 Oct 2023 18:38:43 +0000 x86_64 GNU/Linux

**Comment by razvand** [comment]
@SorinAlexB , @Mihnea0Firoiu , this is probably because you need to use `kraft run -W ...` (the `-W` option is important - it disables the requirement for hardware virtualization). This is because there is no hardware virtualization support for ARM64 when using an x86_64 system.

See if this (the use of the `-W` flag) works. If it does, close this issue.

**Comment by Mihnea0Firoiu** [comment]
Yeah, you are right, it works. Thanks!
